package scan

// extToLanguage maps source extensions; markup/config formats are omitted.
var extToLanguage = map[string]string{
	".go":     "Go",
	".ts":     "TypeScript",
	".tsx":    "TypeScript",
	".js":     "JavaScript",
	".jsx":    "JavaScript",
	".mjs":    "JavaScript",
	".cjs":    "JavaScript",
	".py":     "Python",
	".rb":     "Ruby",
	".java":   "Java",
	".kt":     "Kotlin",
	".kts":    "Kotlin",
	".swift":  "Swift",
	".c":      "C",
	".h":      "C",
	".cpp":    "C++",
	".cc":     "C++",
	".cxx":    "C++",
	".hpp":    "C++",
	".cs":     "C#",
	".rs":     "Rust",
	".php":    "PHP",
	".scala":  "Scala",
	".sh":     "Shell",
	".bash":   "Shell",
	".html":   "HTML",
	".css":    "CSS",
	".scss":   "SCSS",
	".less":   "Less",
	".sql":    "SQL",
	".proto":  "Protocol Buffers",
	".dart":   "Dart",
	".lua":    "Lua",
	".r":      "R",
	".ex":     "Elixir",
	".exs":    "Elixir",
	".erl":    "Erlang",
	".hs":     "Haskell",
	".vue":    "Vue",
	".svelte": "Svelte",
	".zig":    "Zig",
	".clj":    "Clojure",
}
